BASE_URL = 'https://stellarburgers.nomoreparties.site'
REGISTER_USER_URL = f'{BASE_URL}/api/auth/register'
LOGIN_USER_URL = f'{BASE_URL}/api/auth/login'
USER_URL = f'{BASE_URL}/api/auth/user'
ORDER_URL = f'{BASE_URL}/api/orders'
